data:
  features_path: "results/SpectrogramExplainability/FakeRealMusicOriginal/Occlusion/Full_Occlusion_2048_128_all_models/occlusion_features/occlusion_patches"

output:
  result_path: "results/SpectrogramExplainability/FakeRealMusicOriginal/Occlusion/Full_Occlusion_2048_128_all_models/occlusion_features/"