dataset:
  # dictionary with results of occlusion explainability experiment
  occlusion_result_path: "results/SpectrogramExplainability/FakeRealMusicOriginalNormalized/minus23/base/Occlusion/Full_Occlusion_512_512_all_models"

output:
  # dictionary where to save extracted features from occlusion patches
  result_path: "results/SpectrogramExplainability/FakeRealMusicOriginalNormalized/minus23/base/Occlusion/Full_Occlusion_512_512_all_models/occlusion_features"
  experiment_name: "occlusion_patches"

audio:
  samplerate: 44100

occlusion_patches:
  groups: ["best", "worst", "most_influential"]  # available: all, best, worst, most_influential
