# General DSP / processing parameters
sample_rate: 44100
model_time: 120

# Representation
use_mel: false
n_mels: 128

# STFT
n_fft: 2048
hop_length: 512

# Source separation (Spleeter)
use_separation: false
separation_model: "spleeter:4stems" # Options: "spleeter:2stems", "spleeter:4stems", "spleeter:5stems"
separation_targets: ['vocals0', 'drums0', 'bass0', 'other0'] # Depends on the model used

# Normalization of loudness after iSTFT
normalize_loudness: true
lufs: -14
